# MQTT parameters
mqtt:
  client:
    protocol: 4 # MQTTv311
  connection:
    # ---------local-----------
    # host: localhost 
    # port: 1883 
    # -----------aws-----------
    host: a3uloygczce8gz-ats.iot.eu-central-1.amazonaws.com
    port: 8883
    # ------------------------
    keepalive: 60
  # account:
  #   username: "test"
  #   password: "123123"
  private_path: device/022

serializer: json:dumps #msgpack:dumps
deserializer: json:loads #msgpack:loads

#Bridge params
bridge:
  # Odometry bridge
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: nav_msgs.msg:Odometry
    topic_from: /aristos/aristos_base_control/odom
    topic_to: mobile_robot/odometry
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: nav_msgs.msg:Odometry
    topic_from: mobile_robot/odometry
    topic_to: /odometria