# MQTT parameters
mqtt:
  client:
    protocol: 4 # MQTTv311
  connection:
    # ---------local-----------
    # host: localhost 
    # port: 1883 
    # -----------aws-----------
    host: a3uloygczce8gz-ats.iot.eu-central-1.amazonaws.com
    port: 8883
    # ------------------------
    keepalive: 60
  # account:
  #   username: "test"
  #   password: "password"
  private_path: device/001

serializer: json:dumps #msgpack:dumps
deserializer: json:loads #msgpack:loads

# serializer: msgpack:dumps
# deserializer: msgpack:loads

#Bridge params
bridge:
  # Odometry bridge
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: nav_msgs.msg:Odometry
    topic_from: /odometry/gps
    topic_to: mobile_robot/odometry
    
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: nav_msgs.msg:Odometry
    topic_from: mobile_robot/odometry
    topic_to: /odometry/gps_translated

  # - factory: mqtt_bridge.bridge:RosToMqttBridge
  #   msg_type: nav_msgs.msg:Odometry
  #   topic_from: /odom
  #   topic_to: mobile_robot/odometry
    
  # - factory: mqtt_bridge.bridge:MqttToRosBridge
  #   msg_type: nav_msgs.msg:Odometry
  #   topic_from: mobile_robot/odometry
  #   topic_to: /odometria

  # - factory: mqtt_bridge.bridge:RosToMqttBridge
  #   msg_type: std_msgs.msg:String
  #   topic_from: /test
  #   topic_to: mobile_robot/test
  # - factory: mqtt_bridge.bridge:MqttToRosBridge
  #   msg_type: std_msgs.msg:String
  #   topic_from: mobile_robot/test
  #   topic_to: /test_translated